"use server";

import { and, eq, inArray } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { memories, photos } from "@/db/schema";
import { AccessDeniedError, assertCanDeletePhoto, assertOwnsMemory } from "@/lib/access";
import { MaintenanceModeError, assertWritable } from "@/lib/admin";
import { db } from "@/lib/db";
import { requireProfile } from "@/lib/profile";
import { deleteObjects } from "@/lib/storage";
import {
  createMemorySchema,
  memoryIdSchema,
  photoIdSchema,
  photoIdsSchema,
  setCoverSchema,
  toFormState,
  updateMemorySchema,
  type FormState,
} from "@/lib/validation";

/*
 * Memory mutations (FR-MEM-1, 6, 7, 9, 12 and FR-PHOTO-6).
 *
 * Every one: authenticate -> Zod-validate -> authorise through lib/access.ts ->
 * act. No shortcuts, no queries by id alone.
 */

/**
 * `redirect()` and `notFound()` signal control flow by throwing. Catching those
 * would break navigation, so they must always be rethrown.
 */
function isFrameworkSignal(error: unknown): boolean {
  const digest = (error as { digest?: unknown } | null)?.digest;
  return (
    typeof digest === "string" &&
    (digest.startsWith("NEXT_REDIRECT") ||
      digest === "NEXT_NOT_FOUND" ||
      digest.startsWith("NEXT_HTTP_ERROR_FALLBACK"))
  );
}

/** Uniform handling so an authorisation failure never leaks that a row exists. */
function denied(error: unknown, fallback: string): FormState {
  if (error instanceof MaintenanceModeError) {
    return { error: "The app is in maintenance mode. Changes are paused." };
  }
  if (error instanceof AccessDeniedError) {
    return { error: "That memory isn't available." };
  }
  console.error("[memories]", error);
  return { error: fallback };
}

/** FR-MEM-1 — create a memory. The public token is generated by the database. */
export async function createMemoryAction(
  _prev: FormState,
  formData: FormData,
): Promise<FormState> {
  let newId: string;
  try {
    const user = await requireProfile();
    await assertWritable(user.id);
  await assertWritable(user.id);

    const parsed = createMemorySchema.safeParse({
      title: formData.get("title"),
      memoryDate: formData.get("memoryDate"),
    });
    if (!parsed.success) return toFormState(parsed.error);

    const [created] = await db
      .insert(memories)
      .values({
        ownerId: user.id,
        title: parsed.data.title,
        memoryDate: parsed.data.memoryDate,
      })
      .returning({ id: memories.id });
    newId = created.id;
  } catch (error) {
    if (isFrameworkSignal(error)) throw error;
    return denied(error, "We couldn't create that memory.");
  }

  revalidatePath("/memories");
  redirect(`/memories/${newId}`);
}

/** FR-MEM-6 — edit title and date. Owner only (FR-SHARE-5). */
export async function updateMemoryAction(
  _prev: FormState,
  formData: FormData,
): Promise<FormState> {
  const user = await requireProfile();
  await assertWritable(user.id);

  const parsed = updateMemorySchema.safeParse({
    memoryId: formData.get("memoryId"),
    title: formData.get("title"),
    memoryDate: formData.get("memoryDate"),
  });
  if (!parsed.success) return toFormState(parsed.error);

  const { memoryId, title, memoryDate } = parsed.data;

  try {
    await assertOwnsMemory(user.id, memoryId);
    await db
      .update(memories)
      .set({ title, memoryDate, updatedAt: new Date() })
      .where(eq(memories.id, memoryId));
  } catch (error) {
    return denied(error, "We couldn't update that memory.");
  }

  revalidatePath("/memories");
  revalidatePath(`/memories/${memoryId}`);
  return { notice: "Memory updated." };
}

/**
 * FR-MEM-7 — delete a memory, its photos, and their stored files.
 *
 * The DB row goes first (cascades to photos), then storage. If storage deletion
 * fails we log loudly rather than throw: the user's delete has already
 * succeeded, and re-throwing would tell them it failed when it didn't. Orphaned
 * objects are a billing and hygiene problem to reconcile, not a reason to
 * refuse the operation.
 */
export async function deleteMemoryAction(formData: FormData): Promise<void> {
  const user = await requireProfile();
  await assertWritable(user.id);

  const parsed = memoryIdSchema.safeParse({ memoryId: formData.get("memoryId") });
  if (!parsed.success) return;

  const { memoryId } = parsed.data;

  await assertOwnsMemory(user.id, memoryId);

  const doomed = await db
    .select({ storageKey: photos.storageKey, thumbnailKey: photos.thumbnailKey })
    .from(photos)
    .where(eq(photos.memoryId, memoryId));

  const [memory] = await db
    .select({
      coverImageKey: memories.coverImageKey,
      coverThumbnailKey: memories.coverThumbnailKey,
    })
    .from(memories)
    .where(eq(memories.id, memoryId))
    .limit(1);

  const keys = [
    ...doomed.flatMap((p) => [p.storageKey, p.thumbnailKey]),
    memory?.coverImageKey,
    memory?.coverThumbnailKey,
  ].filter((key): key is string => Boolean(key));

  await db.delete(memories).where(eq(memories.id, memoryId));

  try {
    await deleteObjects(keys);
  } catch (error) {
    console.error(
      `[memories] orphaned ${keys.length} storage objects for memory ${memoryId}`,
      error,
    );
  }

  revalidatePath("/memories");
  redirect("/memories");
}

/** FR-MEM-9/12 — set the cover to one of the memory's own photos. */
export async function setCoverAction(formData: FormData): Promise<FormState> {
  const user = await requireProfile();
  await assertWritable(user.id);

  const parsed = setCoverSchema.safeParse({
    memoryId: formData.get("memoryId"),
    photoId: formData.get("photoId"),
  });
  if (!parsed.success) return toFormState(parsed.error);

  const { memoryId, photoId } = parsed.data;

  try {
    await assertOwnsMemory(user.id, memoryId);

    // The photo must belong to THIS memory — otherwise an owner could point a
    // cover at a photo in someone else's album and leak its thumbnail.
    const [photo] = await db
      .select({ id: photos.id })
      .from(photos)
      .where(and(eq(photos.id, photoId), eq(photos.memoryId, memoryId)))
      .limit(1);
    if (!photo) return { error: "That photo isn't in this memory." };

    await db
      .update(memories)
      .set({ coverSource: "photo", coverPhotoId: photoId, updatedAt: new Date() })
      .where(eq(memories.id, memoryId));
  } catch (error) {
    return denied(error, "We couldn't set that cover.");
  }

  revalidatePath("/memories");
  revalidatePath(`/memories/${memoryId}`);
  return { notice: "Cover updated." };
}

/** FR-MEM-11/D11 — go back to the automatic cover. */
export async function clearCoverAction(formData: FormData): Promise<FormState> {
  const user = await requireProfile();
  await assertWritable(user.id);

  const parsed = memoryIdSchema.safeParse({ memoryId: formData.get("memoryId") });
  if (!parsed.success) return toFormState(parsed.error);

  const { memoryId } = parsed.data;

  try {
    await assertOwnsMemory(user.id, memoryId);

    const [memory] = await db
      .select({
        coverImageKey: memories.coverImageKey,
        coverThumbnailKey: memories.coverThumbnailKey,
      })
      .from(memories)
      .where(eq(memories.id, memoryId))
      .limit(1);

    await db
      .update(memories)
      .set({
        coverSource: "auto",
        coverPhotoId: null,
        coverImageKey: null,
        coverThumbnailKey: null,
        updatedAt: new Date(),
      })
      .where(eq(memories.id, memoryId));

    // A custom cover's files exist only for the cover, so clearing it must
    // remove them or they are orphaned immediately.
    const keys = [memory?.coverImageKey, memory?.coverThumbnailKey].filter(
      (key): key is string => Boolean(key),
    );
    if (keys.length) await deleteObjects(keys);
  } catch (error) {
    return denied(error, "We couldn't reset that cover.");
  }

  revalidatePath("/memories");
  revalidatePath(`/memories/${memoryId}`);
  return { notice: "Cover reset." };
}

/** FR-PHOTO-6 — delete a photo and its stored files. D10 limits contributors. */
export async function deletePhotoAction(formData: FormData): Promise<void> {
  const user = await requireProfile();
  await assertWritable(user.id);

  const parsed = photoIdSchema.safeParse({ photoId: formData.get("photoId") });
  if (!parsed.success) return;

  const photo = await assertCanDeletePhoto(user.id, parsed.data.photoId);

  await db.delete(photos).where(eq(photos.id, photo.id));

  try {
    await deleteObjects([photo.storageKey, photo.thumbnailKey]);
  } catch (error) {
    console.error(`[memories] orphaned storage for photo ${photo.id}`, error);
  }

  revalidatePath("/memories");
  revalidatePath(`/memories/${photo.memoryId}`);
}

/**
 * FR-PHOTO-6, bulk — delete several photos at once.
 *
 * Every id is authorised individually through `assertCanDeletePhoto` (D10), so
 * slipping someone else's photo id into the list gets that one id rejected
 * rather than deleted. Photos the caller may not delete are skipped silently:
 * reporting them would confirm the ids exist.
 */
export async function deletePhotosAction(formData: FormData): Promise<FormState> {
  const user = await requireProfile();
  await assertWritable(user.id);

  const parsed = photoIdsSchema.safeParse({
    photoIds: formData.getAll("photoId").map(String),
  });
  if (!parsed.success) return toFormState(parsed.error);

  const keys: string[] = [];
  const ids: string[] = [];
  let memoryId: string | null = null;

  for (const photoId of parsed.data.photoIds) {
    try {
      const photo = await assertCanDeletePhoto(user.id, photoId);
      ids.push(photo.id);
      keys.push(photo.storageKey, photo.thumbnailKey);
      memoryId ??= photo.memoryId;
    } catch (error) {
      if (error instanceof AccessDeniedError) continue;
      throw error;
    }
  }

  if (ids.length === 0) {
    return { error: "Those photos aren't available." };
  }

  await db.delete(photos).where(inArray(photos.id, ids));

  try {
    await deleteObjects(keys);
  } catch (error) {
    console.error(`[memories] orphaned ${keys.length} storage objects`, error);
  }

  revalidatePath("/memories");
  if (memoryId) revalidatePath(`/memories/${memoryId}`);

  const skipped = parsed.data.photoIds.length - ids.length;
  return {
    notice:
      skipped > 0
        ? `Deleted ${ids.length} of ${parsed.data.photoIds.length} photos.`
        : `Deleted ${ids.length} ${ids.length === 1 ? "photo" : "photos"}.`,
  };
}
