import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  date,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/*
 * Memories database schema — implements docs/Memories-Implementation-Plan.md §5.
 *
 * Auth tables (users, sessions, OAuth) are owned by Neon Auth in the `neon_auth`
 * schema and must NOT be re-created here. `profiles` holds only app-specific user
 * data, keyed by the Neon Auth user id.
 */

/**
 * FR-QUOTA-1 / D26 — the default per-user storage allowance: 20 GB.
 *
 * Declared here because it is a column default; `lib/storage-quota.ts` owns the
 * behaviour built on it. Read a user's own `storageQuotaBytes` rather than this
 * constant when checking anything — the whole point of the column is that the
 * two can differ.
 */
export const DEFAULT_STORAGE_QUOTA_BYTES = 20 * 1024 * 1024 * 1024;

// ---------------------------------------------------------------------------
// Profiles — app-specific user data, 1:1 with the Neon Auth user
// ---------------------------------------------------------------------------

export const profiles = pgTable("profiles", {
  /** Neon Auth user id (text, not uuid — the auth provider owns the format). */
  id: text("id").primaryKey(),
  displayName: text("display_name").notNull(),
  /**
   * D22 — requirements §2 reserved this field "for future use"; the admin
   * console is that future use. Held here rather than in Neon Auth's own `role`
   * column so authorization never depends on a beta SDK whose admin endpoints
   * were found returning 404.
   */
  role: text("role", { enum: ["user", "admin"] })
    .notNull()
    .default("user"),
  /**
   * D22 — set when an admin deactivates the account. Enforced on every
   * authenticated request in `requireProfile`, so a deactivated user is locked
   * out even though their Neon Auth session technically still exists.
   */
  deactivatedAt: timestamp("deactivated_at", { withTimezone: true }),
  /**
   * FR-PROF-4 / NFR-OPT: always true. Surfaced in settings as an ON, read-only
   * control. The column exists so the UI has something to render, not so the
   * value can vary — never write `false` here.
   */
  imageOptimizationEnabled: boolean("image_optimization_enabled")
    .notNull()
    .default(true),
  /**
   * FR-QUOTA-1 / D26 — how much storage this user's own memories may hold.
   *
   * Per-user rather than an app constant so a future paid tier (FF-BILLING) can
   * raise one account with an UPDATE instead of a migration. The value is a
   * ceiling on *owned* memories: what the user uploaded elsewhere is charged to
   * that memory's owner, not here (FR-QUOTA-2).
   */
  storageQuotaBytes: bigint("storage_quota_bytes", { mode: "number" })
    .notNull()
    .default(DEFAULT_STORAGE_QUOTA_BYTES),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// Memories (albums)
// ---------------------------------------------------------------------------

export const memories = pgTable(
  "memories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    /** FR-MEM-1 / D2: user-set, defaults to today in the UI, editable. */
    memoryDate: date("memory_date").notNull(),

    /** FR-MEM-9/10/11: how the cover is resolved. */
    coverSource: text("cover_source", { enum: ["auto", "photo", "custom"] })
      .notNull()
      .default("auto"),
    /**
     * Lazy reference: memories -> photos -> memories is circular, so the target
     * must be resolved through a callback. D11 — on cover photo deletion this
     * goes null and the app reverts cover_source to 'auto'.
     */
    coverPhotoId: uuid("cover_photo_id").references(
      (): AnyPgColumn => photos.id,
      { onDelete: "set null" },
    ),
    /** FR-MEM-10: custom cover upload; never appears in the photo grid. */
    coverImageKey: text("cover_image_key"),
    coverThumbnailKey: text("cover_thumbnail_key"),

    /**
     * FR-SHARE-7 / NFR-SEC: 128 bits of entropy, generated by the database so a
     * memory can never exist without a token. Needs the pgcrypto extension.
     */
    publicToken: text("public_token")
      .notNull()
      .unique()
      .default(sql`encode(gen_random_bytes(16), 'hex')`),
    /** D8: active from creation. FR-SHARE-10 revoke sets this false. */
    publicLinkActive: boolean("public_link_active").notNull().default(true),
    /**
     * D21 — lets anyone holding the public link ADD photos, not just view.
     *
     * Off by default and per-memory: this is the only setting in the app that
     * opens an unauthenticated write path, so it must always be a deliberate,
     * explicit act by the owner. Amends FR-SHARE-9.
     */
    publicCanContribute: boolean("public_can_contribute")
      .notNull()
      .default(false),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("memories_owner_id_idx").on(table.ownerId),
    check(
      "memories_cover_source_check",
      sql`${table.coverSource} in ('auto','photo','custom')`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Photos
// ---------------------------------------------------------------------------

export const photos = pgTable(
  "photos",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    memoryId: uuid("memory_id")
      .notNull()
      .references(() => memories.id, { onDelete: "cascade" }),
    /**
     * May differ from the memory owner in a shared memory (D10).
     *
     * NULL means an anonymous guest upload via a public link (D21). Since there
     * is no account behind it, D10's "contributors may delete their own
     * uploads" cannot apply — only the memory owner can delete a guest upload.
     */
    uploadedBy: text("uploaded_by").references(() => profiles.id),

    /**
     * FR-VIDEO-1 / D23 — what kind of media this row holds.
     *
     * Defaults to 'image' so every row that existed before video support keeps
     * its meaning without a backfill. The two types share this table rather than
     * getting one of their own because everything around them — ordering, access,
     * cover resolution, deletion, the grid — treats them identically; only
     * decoding and playback differ.
     */
    mediaType: text("media_type", { enum: ["image", "video"] })
      .notNull()
      .default("image"),

    /**
     * Object-storage keys. High-entropy so URLs are not enumerable.
     *
     * For a video, `storage_key` is the video file as uploaded (D23 — no
     * transcode) and `thumbnail_key` is the WebP poster frame, so every caller
     * that just wants "the picture for this row" needs no special case.
     */
    storageKey: text("storage_key").notNull(),
    thumbnailKey: text("thumbnail_key").notNull(),

    originalFilename: text("original_filename"),
    mimeType: text("mime_type").notNull(),
    width: integer("width"),
    height: integer("height"),
    optimizedSizeBytes: bigint("optimized_size_bytes", { mode: "number" }),
    /**
     * FR-QUOTA-3 — size of `thumbnail_key`'s object (the thumbnail, or a
     * video's poster frame).
     *
     * Exists because `optimized_size_bytes` covers only the full-size asset,
     * and a quota summing that column alone undercounts every image by ~6.6%
     * (measured: 198 KB full-size against a 13 KB thumbnail). Nullable
     * because rows written before Phase 7 have no value until the backfill
     * script fills them in; the usage query coalesces, so those rows
     * undercount rather than break.
     */
    thumbnailSizeBytes: bigint("thumbnail_size_bytes", { mode: "number" }),
    /** Pre-optimization size. Never counted against quota — D5 discards it. */
    originalSizeBytes: bigint("original_size_bytes", { mode: "number" }),

    /**
     * FR-VIDEO-5 — playback length, read from the browser's own decode of the
     * file before upload. Null for images.
     */
    durationSeconds: integer("duration_seconds"),

    /**
     * NFR-OPT: extracted from EXIF *before* metadata is stripped.
     *
     * Always null for video (D23): container creation timestamps are absent or
     * zeroed often enough to be worse than no value at all, so videos sort by
     * upload time via the coalesce in FR-PHOTO-7's ordering.
     */
    takenAt: timestamp("taken_at", { withTimezone: true }),

    sortOrder: integer("sort_order").notNull().default(0),
    status: text("status", { enum: ["uploading", "ready", "failed"] })
      .notNull()
      .default("ready"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("photos_memory_id_idx").on(table.memoryId),
    check(
      "photos_status_check",
      sql`${table.status} in ('uploading','ready','failed')`,
    ),
    check("photos_media_type_check", sql`${table.mediaType} in ('image','video')`),
  ],
);

// ---------------------------------------------------------------------------
// Sharing membership (FR-SHARE-1..6)
// ---------------------------------------------------------------------------

export const memoryShares = pgTable(
  "memory_shares",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    memoryId: uuid("memory_id")
      .notNull()
      .references(() => memories.id, { onDelete: "cascade" }),

    /**
     * D13 — nullable, unlike plan §5. A share may be addressed to someone who
     * has no account yet: then `user_id` is null and `invited_email` carries the
     * address until they sign up and the invite is claimed.
     */
    userId: text("user_id").references(() => profiles.id, {
      onDelete: "cascade",
    }),
    /** D13 — set for invites to a not-yet-registered address. */
    invitedEmail: text("invited_email"),

    permission: text("permission", { enum: ["viewer", "contributor"] }).notNull(),
    invitedBy: text("invited_by")
      .notNull()
      .references(() => profiles.id),
    /**
     * D14 — 'accepted' is written directly when sharing with an existing user
     * (the email is a notification, not a gate). Email invites to non-users
     * start 'pending' and flip to 'accepted' when the address is claimed at
     * sign-up. The access helper only ever grants on 'accepted'.
     */
    status: text("status", { enum: ["pending", "accepted", "revoked"] })
      .notNull()
      .default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("memory_shares_user_id_idx").on(table.userId),
    /*
     * Plan §5 used `unique (memory_id, user_id)`. With user_id nullable that no
     * longer prevents duplicates, because Postgres treats NULLs as distinct in a
     * unique constraint — every email invite would slip past it. Two partial
     * unique indexes restore the intent on both addressing modes.
     */
    uniqueIndex("memory_shares_memory_user_uniq")
      .on(table.memoryId, table.userId)
      .where(sql`${table.userId} is not null`),
    uniqueIndex("memory_shares_memory_email_uniq")
      .on(table.memoryId, sql`lower(${table.invitedEmail})`)
      .where(sql`${table.invitedEmail} is not null`),
    check(
      "memory_shares_target_check",
      sql`${table.userId} is not null or ${table.invitedEmail} is not null`,
    ),
    check(
      "memory_shares_permission_check",
      sql`${table.permission} in ('viewer','contributor')`,
    ),
    check(
      "memory_shares_status_check",
      sql`${table.status} in ('pending','accepted','revoked')`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Social — Phase 4. D9: photo-level only for v1.
// ---------------------------------------------------------------------------

export const comments = pgTable(
  "comments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    photoId: uuid("photo_id").references(() => photos.id, {
      onDelete: "cascade",
    }),
    userId: text("user_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("comments_photo_id_idx").on(table.photoId)],
);

export const likes = pgTable(
  "likes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    photoId: uuid("photo_id").references(() => photos.id, {
      onDelete: "cascade",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("likes_user_photo_uniq").on(table.userId, table.photoId),
  ],
);

/** FR-SOC-4 / A8: people, not keyword tags. */
export const persons = pgTable("persons", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerUserId: text("owner_user_id")
    .notNull()
    .references(() => profiles.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  /** Set when the person is also an app user (enables self-removal, FR-SOC-5). */
  linkedUserId: text("linked_user_id").references(() => profiles.id),
});

export const photoTags = pgTable("photo_tags", {
  id: uuid("id").primaryKey().defaultRandom(),
  photoId: uuid("photo_id")
    .notNull()
    .references(() => photos.id, { onDelete: "cascade" }),
  personId: uuid("person_id").references(() => persons.id, {
    onDelete: "cascade",
  }),
  taggedBy: text("tagged_by")
    .notNull()
    .references(() => profiles.id),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// ---------------------------------------------------------------------------
// Global application settings (D22)
// ---------------------------------------------------------------------------

/**
 * Single-row table holding app-wide switches.
 *
 * A table rather than an env var because maintenance mode has to be flipped by
 * an admin at runtime, without a redeploy — a redeploy is exactly what you
 * can't rely on when you need to freeze the app.
 */
export const appSettings = pgTable("app_settings", {
  /** Always 'global'. The check constraint enforces the single row. */
  id: text("id").primaryKey().default("global"),
  maintenanceMode: boolean("maintenance_mode").notNull().default(false),
  updatedBy: text("updated_by").references(() => profiles.id),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
